// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "./Visibility";

export type AddSystemRequest = { name: string, 
/**
 * Frequency in minutes
 */
frequency: bigint, starts_at: string, 
/**
 * Time in minutes after which the user will get emailed
 */
down_after: bigint, visibility: Visibility, };
