// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type Instant = {
  status: Status;
  timestamp: string | null;
  expected_timestamp: string;
};
