/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/list_systems': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Systems */
		get: operations['list_systems'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/healthcheck': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Healthcheck
		 * @description Check if the server is running
		 */
		get: operations['healthcheck'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/user/get_current_settings': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Retrieve Settings */
		get: operations['get_current_settings'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/delete_system': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete System */
		delete: operations['delete_system'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/change_visibility': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Change Visibility
		 * @description Change the visibility of a system
		 */
		patch: operations['change_visibility'];
		trace?: never;
	};
	'/ping_status/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Ping as system
		 * @description Ping this endpoint to update the status of the system
		 */
		post: operations['ping_status'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/edit_system_name': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Edit Name */
		patch: operations['edit_system_name'];
		trace?: never;
	};
	'/user/change_language': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Change Language */
		patch: operations['change_language'];
		trace?: never;
	};
	'/user/change_password': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Change Password */
		patch: operations['change_password'];
		trace?: never;
	};
	'/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Logout
		 * @description Logout the current user
		 */
		get: operations['logout'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/add_system': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add System */
		post: operations['add_system'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Login
		 * @description Login or sign up a user if it does not exist
		 */
		post: operations['login'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sys_info': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * System information
		 * @description Get system information
		 */
		get: operations['sys_info'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/get_public/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieve Info
		 * @description Retrieve info about a public system
		 */
		get: operations['get_public'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/user/change_timezone': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Change Timezone */
		patch: operations['change_timezone'];
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ChangePasswordRequest: {
			/** @description The old password */
			old_password: string;
			/** @description The new password */
			new_password: string;
		};
		/** @enum {string} */
		Status: 'up' | 'down' | 'untracked';
		/** @enum {string} */
		Visibility: 'public' | 'private';
		ListSystemsResponse: {
			/** @description The list of systems that the user has */
			systems: components['schemas']['SystemData'][];
		};
		AddSystemResponse: {
			/**
			 * Format: uuid
			 * @description The ID of the system that was created
			 */
			id: string;
		};
		ChangeLanguageRequest: {
			/** @description The new language, as defined by the IETF language tag */
			language: string;
		};
		AddSystemRequest: {
			/** @description The name of the system */
			name: string;
			/**
			 * Format: date-time
			 * @description The time at which the system starts pinging
			 */
			starts_at: string;
			/**
			 * Format: int64
			 * @description The frequency in minutes of the pings
			 */
			frequency: number;
			/** @description The visibility of the system */
			visibility: components['schemas']['Visibility'];
			/**
			 * Format: int64
			 * @description Time in minutes after which the user will get emailed
			 */
			down_after: number;
		};
		ChangeTimezoneRequest: {
			/** @description The new timezone, as defined by the IANA Time Zone Database */
			timezone: string;
		};
		CpuInfo: {
			/** Format: float */
			usage: number;
			brand: string;
			frequency: string;
			name: string;
			vendor_id: string;
		};
		GetCurrentSettingsResponse: {
			/**
			 * @description The current timezone of the user, as defined by the IANA Time Zone
			 *     Database
			 */
			timezone: string;
			/** @description The current language of the user, as defined by the IETF language tag */
			language: string;
		};
		DeleteSystemRequest: {
			/**
			 * Format: uuid
			 * @description The ID of the system to delete
			 */
			id: string;
		};
		LoginResponse: {
			status: string;
		};
		SwapInfo: {
			free: string;
			total: string;
			used: string;
		};
		GetPublicResponse: {
			/** @description The requested system's data */
			system: components['schemas']['SystemData'];
		};
		ChangeVisibilityRequest: {
			/**
			 * Format: uuid
			 * @description The ID of the system
			 */
			id: string;
			/** @description The new visibility of the system */
			visibility: components['schemas']['Visibility'];
		};
		EditSystemNameRequest: {
			/**
			 * Format: uuid
			 * @description The ID of the system
			 */
			id: string;
			/** @description The new name of the system */
			name: string;
		};
		SystemData: {
			/**
			 * Format: int32
			 * @description Frequency in minutes
			 */
			frequency: number;
			/** @description The visibility of the system */
			visibility: components['schemas']['Visibility'];
			/**
			 * @description The list of instants (containing states for each expected ping) for the
			 *     system
			 */
			instants: components['schemas']['Instant'][];
			/**
			 * Format: uuid
			 * @description The ID of the system
			 */
			id: string;
			/** @description The name of the system */
			name: string;
			/**
			 * Format: date-time
			 * @description The time at which the system starts pinging
			 */
			starts_at: string;
		};
		SystemInfoResponse: {
			cpu_info: components['schemas']['CpuInfo'];
			memory: components['schemas']['MemInfo'];
			swap: components['schemas']['SwapInfo'];
			basic: components['schemas']['BasicSystemInfo'];
		};
		Instant: {
			/** @description The status of the system at this instant */
			status: components['schemas']['Status'];
			/**
			 * Format: date-time
			 * @description The expected timestamp of the ping (calculated from the frequency and
			 *     the start time)
			 */
			expected_timestamp: string;
			/**
			 * Format: date-time
			 * @description The actual timestamp of the ping
			 */
			timestamp?: string | null;
		};
		BasicSystemInfo: {
			system_name: string;
			system_kernel_version: string;
			system_host_name: string;
			system_os_version: string;
		};
		Credentials: {
			/** @description The password of the user */
			password: string;
			/** @description The email of the user */
			email: string;
		};
		MemInfo: {
			free: string;
			total: string;
			used: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_systems: {
		parameters: {
			query: {
				/** @description The page number to return */
				page: number;
				/** @description The maximum number of instants to return */
				list_size: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of systems */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ListSystemsResponse'];
				};
			};
			/** @description Bad request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	healthcheck: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Healthcheck was successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_current_settings: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current settings were retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetCurrentSettingsResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_system: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DeleteSystemRequest'];
			};
		};
		responses: {
			/** @description System was deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	change_visibility: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ChangeVisibilityRequest'];
			};
		};
		responses: {
			/** @description Visibility was changed successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	ping_status: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Ping was successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description System not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	edit_system_name: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EditSystemNameRequest'];
			};
		};
		responses: {
			/** @description System name was edited successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	change_language: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ChangeLanguageRequest'];
			};
		};
		responses: {
			/** @description Language was changed successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Language is not valid */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example Language is not valid */
					'text/plain': string;
				};
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example User is not logged in */
					'text/plain': string;
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example Failed to update language */
					'text/plain': string;
				};
			};
		};
	};
	change_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ChangePasswordRequest'];
			};
		};
		responses: {
			/** @description Password was changed successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example User is not logged in */
					'text/plain': string;
				};
			};
			/** @description Old password is wrong */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example Old password is wrong */
					'text/plain': string;
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User was logged out */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_system: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddSystemRequest'];
			};
		};
		responses: {
			/** @description System was created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AddSystemResponse'];
				};
			};
			/** @description Bad request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['Credentials'];
			};
		};
		responses: {
			/** @description User was logged in */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LoginResponse'];
				};
			};
			/** @description User was created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LoginResponse'];
				};
			};
			/** @description Wrong password */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
		};
	};
	sys_info: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description System information was retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SystemInfoResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_public: {
		parameters: {
			query: {
				/** @description The maximum number of instants to return */
				list_size: number;
				/** @description The page number to return */
				page: number;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Public system was retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetPublicResponse'];
				};
			};
			/** @description List size is too large */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description System not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	change_timezone: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ChangeTimezoneRequest'];
			};
		};
		responses: {
			/** @description Timezone was changed successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Timezone is not valid */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example Timezone not valid */
					'text/plain': string;
				};
			};
			/** @description User is not logged in */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example User is not logged in */
					'text/plain': string;
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					/** @example Failed to update timezone */
					'text/plain': string;
				};
			};
		};
	};
}
