use std::{
    ffi::OsStr,
    fs::{self, File},
    io::Write,
};

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo::rerun-if-changed=bindings/*");

    gen_binding_index();
}

// From https://github.com/Aleph-Alpha/ts-rs/issues/133#issuecomment-1399589933
fn gen_binding_index() {
    println!("Generating bindings/index.ts");

    if let Ok(exports) = fs::read_dir("./bindings") {
        let exports: Vec<_> = exports
            .filter_map(Result::ok)
            .filter_map(|p| {
                p.path()
                    .file_stem()
                    .and_then(OsStr::to_str)
                    .map(str::to_owned)
            })
            .filter(|f| f != "index")
            .map(|f| format!("export * from \"./{}\"", f))
            .collect();

        let mut file = File::create("./bindings/index.ts").unwrap();
        file.write_all(exports.join("\n").as_bytes()).unwrap();

        println!("Generated bindings/index.ts");
    } else {
        eprintln!("Cannot generate bindings/index.ts, bindings directory not found");
    }
}
