[package]
name = "monitor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.74"
axum = "0.7.0"
axum-login = "0.16.0"
http = "1.0.0"
hyper = "1.0.1"
password-auth = "1.0.0"
serde = "1"
sqlx = { version = "0.8.1", features = ["postgres", "time", "runtime-tokio-native-tls", "uuid", "chrono"] }
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full"] }
tower = "0.5.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower-sessions = { version = "0.13.0", default-features = false, features = [
    "signed",
] }
tower-sessions-sqlx-store = { version = "0.14.0", features = ["postgres"] }
thiserror = "1.0.56"
dotenvy = "0.15.7"
color-eyre = "0.6.3"
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
chrono = "0.4.38"
ts-rs = { version = "9.0.1", features = ["serde-json-impl", "uuid-impl", "format"] }
axum_thiserror = "0.1.0"

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.sqlx-macros]
opt-level = 3
