#[config]
#default_to_workspace = false

[tasks.generate-ts]
env = { "TS_RS_EXPORT_DIR" = "../frontend/src/lib/bindings" }
command = "cargo"
args = ["test"]

[tasks.pull-translations]
command = "tolgee"
args = ["pull"]
dependencies = ["get-translations"]

[tasks.get-translations]
command = "./i18n/prepare-translations.sh"

