[variables]
RUSTFLAGS = '-C link-arg=-fuse-ld=mold'

[phases.build]
nixPkgs = ['mold']
cmds = ['mkdir -p bin', 'RUSTFLAGS="-C link-arg=-fuse-ld=mold" cargo build --release', 'cp target/release/monitor bin/']

[start]
runImage = 'alpine:latest'
cmd = './bin/monitor'