[variables]
RUSTFLAGS = '-C link-arg=-fuse-ld=mold'

[phases.build]
nixPkgs = ['mold']
cmds = ['mkdir -p bin', 'cargo build --release', 'cp target/release/monitor bin/', 'cp -r config/ bin/']

[start]
cmd = './bin/monitor'