// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginStatus } from "./LoginStatus";

export type LoginStatusResponse = { status: LoginStatus; email: string | null };
